import Head from 'next/head'
import Header from '../components/Header'
import Hero from '../components/Hero'
import Join from '../components/Join'
import { BsPatchCheckFill, BsWhatsapp } from 'react-icons/bs'
import { RiMailSendFill } from 'react-icons/ri'
import { SiMinutemailer } from 'react-icons/si'
import styles from '../styles/Home.module.css'
import Schedules from '../components/Schedules'
import Reels from '../components/Reels'
import ClientSay from '../components/ClientSay'
import { AiFillInstagram } from 'react-icons/ai'
import LastedBowlsNews from '../components/LastedBowlsNews'
import Footer from '../components/Footer'
export default function Home() {
  return (
    <div className='min-w-fit'>
      <Head >
        <title>BOWLING APP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Hero />
      <Join />
      <div className=' bg-gray-100'>
        <div className='max-w-7xl  mx-auto space-y-10 gap-x-4 lg:space-y-0 lg:h-80 flex flex-col lg:flex-row justify-between'>
          <div className=' pt-10 2xl:pt-20 flex-1 px-3 md:px-0'>
            <h2 className='font-semibold mb-6'>WHAT YOU SHOULD KNOW</h2>
            <ul className='space-y-2 text-sm'>
              <li className='flex items-center gap-1'><BsPatchCheckFill className='text-blue-700' /> Show/swipe your membership card at reception</li>
              <li className='flex items-center gap-1'><BsPatchCheckFill className='text-blue-700' /> You must sign in and provide proof of ID at reception</li>
              <li className='flex items-center gap-1'><BsPatchCheckFill className='text-blue-700' />You must live outside of a 15milles radius to be able to sign in as a vistor</li>
              <li className='flex items-center gap-1'><BsPatchCheckFill className='text-blue-700' />You must remain in the company of the member whilst in the club</li>
              <li className='flex items-center gap-1'><BsPatchCheckFill className='text-blue-700' />Provide acceptable evidence of age where there is any doubt under 25</li>
            </ul>
          </div>
          <img
            className='w-full flex-1 lg:w-fit h-72  object-cover lg:h-full '
            src='https://trindlebowl.net/wp-content/uploads/sites/5/2020/01/Family-bowling7.jpg' />
        </div>
        <div className=' justify-center py-6 text-base md:text-xl 
         gap-x-2 text-white bg-blue-700 flex items-center'>
          <BsWhatsapp className='text-blue-600' />
          Reservations: 555 - 345 6789 </div>
      </div>
      <Schedules />
      <div className='bg-blue-700 py-5 '>
        <div className='container mx-auto'>
          <div className='flex gap-y-3 px-3 md:px-0 lg:items-center flex-col lg:flex-row'>
            <p className='flex items-center gap-x-1 flex-1 text-gray-50 text-sm'>
              <RiMailSendFill className='bg-blue-500 text-blue-700 p-2 rounded-full' size={30} />
              SIGN UP TO OUR NEWSLETTER FOR OUR BEST OFFERS
            </p>
            <div className='flex-1 relative'>
              <SiMinutemailer className='absolute right-5 top-1/2 -mt-3' size={20} />
              <input placeholder='Email Address ' className='text-sm  w-full py-3 pl-5 pr-10' />
            </div>
          </div>
        </div>
      </div>
      <Reels />
      <ClientSay />

      <div className='bg-gray-900 py-5 '>
        <div className='max-w-7xl mx-auto'>
          <div className='flex items-center'>
            <p className='flex items-center gap-x-1 flex-1 text-gray-50 text-lg font-semibold'>
              INSTAGRAM FEED
            </p>
            <div className=''>
              <button className='
              text-gray-400 flex items-center gap-x-2  
              rounded-2xl border border-gray-400 px-7 py-2
              hover:bg-white hover:text-gray-900 ease-in-out transition-all hover:border-white
              '><AiFillInstagram size={20} />Follow Us</button>
            </div>
          </div>
        </div>
      </div>

      <Reels instragramreel={true} />
      <LastedBowlsNews />
      <Footer />
    </div>
  )
}
